WebApplication1/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WebApplication1.Areas.HelpPage.ModelDescriptions;
using WebApplication1.Areas.HelpPage.Models;

namespace WebApplication1.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_LayoutNew.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title></title>
    @Styles.Render("~/Content/style")
    
</head>

<body>
    @RenderBody()
</body>

</html>

WebApplication1/Views/Shared/_NovaLoginPartial.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <div id="divLogin" class="login-block">
            <form id="formInput" class="loginPanel" role="form" action="rule.html">
                <div class="form-group">
                    <div class="inputPanel">
                        <input id="Username" class="form-control" type="text" placeholder="Username">
                        <input id="Password" class="form-control" type="password" placeholder="Password">
                        <div class="btn btn-cancel" role="button"><i class="icon icon-cancel"></i></div>
                    </div>
                    <div id="warringMessageFade" class="tooltip bottom fade" role="tooltip">
                        <div class="tooltip-arrow"></div>
                        <div id="warringMessage" class="tooltip-inner"></div>
                    </div>
                    <button id="LoginBtn" type="button" class="btn btn-primary btn-block btn-login" onclick="login(event)">Login</button>
                </div>
            </form>
        </div>
    </div>
</body>
<script src="Scripts/require.js"></script>
<script src="Scripts/require_config.js"></script>
<script>
    //todo 應該在main.js & 使用bundles
    require(['react'], function (React) {
        window["React"] = React;
        if (!React.render) {
            require(['create-react-class', 'react-dom'], function (createClass, reactDom) {
                if (!React.createClass) React.createClass = createClass;
                if (!React.findDOMNode) React.findDOMNode = reactDom.findDOMNode;
                if (!React.render) React.render = reactDom.render;
                if (!React.unmountComponentAtNode) React.unmountComponentAtNode = reactDom.unmountComponentAtNode;
            });
        }

    });

    function DomObj(name) {
        return document.getElementById(name);
    }

    function login(e) {
        e.stopPropagation();
        var Username = DomObj('Username').value.toLowerCase();
        var Password = DomObj('Password').value;

        require(['jquery', 'common'], function ($, common) {

            var data = { Username: Username, Password: Password };
            common.SyncServer(
                'Login/index',
                data,
                function (val) {
                    loginResult(val);
                }.bind(this),
                false,
                $
            );
        });
    }

    function loginResult(val) {
        console.log(val);

        var success = false;
        var errMsg = "";

        require(['backbone', 'router'], function (Backbone, router) {
            Backbone.history.start();
        });

        success = true;

        return {
            success: success,
            errMsg: errMsg
        }
    }
</script>
</html>